### ISSUE TITLE
using Basler camera with deeplabcut-live-GUI

### ISSUE THREAD

**Issue by NadineKGut** [DeepLabCut/DeepLabCut-live-GUI#27]
Hi,

I cannot make our Basler camera work with deeplabcut-live-GUI. I tried to follow the suggestions here https://github.com/DeepLabCut/DeepLabCut-live-GUI/blob/master/docs/camera_support.md and installed pylon viewer, pypylon, and swig, but it is still not working. I get no cameras to select in the drop down menu and this error message:

Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\TDT\anaconda3\envs\dlc-live\lib\tkinter_init_.py", line 1892, in call return self.func(*args) File "C:\Users\TDT\anaconda3\envs\dlc-live\lib\site-packages\dlclivegui\dlclivegui.py", line 317, in edit_cam_settings arg_names, arg_vals, arg_dtypes, arg_restrict = self.get_cam_args() File "C:\Users\TDT\anaconda3\envs\dlc-live\lib\site-packages\dlclivegui\dlclivegui.py", line 380, in get_cam_args cam_obj = getattr(camera, this_cam["type"]) TypeError: 'NoneType' object is not subscriptable

The fix was described for Ubuntu. Maybe this does not work for Windows?

Any advice would be very helpful. Thank you
Nadine

**Comment by the-firetorch** [comment]
Hi, I encountered the same problem but by:
1. Downloading the basler camera python file  "https://github.com/DeepLabCut/DeepLabCut-live-GUI/blob/master/dlclivegui/camera/basler.py" and putting that in the cameras folder in the dlc-live solves the job. 
2. You also need to write the importing statement "from dlclivegui.camera.basler import BaslerCam" inside the __init__.py  file/

You can now see your basler camera inside the 'Add Camera' inside the dlc-live gui :)
